package ytm

import (
	"database/sql"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"

	_ "modernc.org/sqlite"
)

var (
	// ErrBrowserNotFound 浏览器未安装或未找到配置。
	ErrBrowserNotFound = errors.New("浏览器未安装或未找到配置")
	// ErrDecryptFailed cookie 解密失败（密钥不可用/密文损坏）。
	ErrDecryptFailed = errors.New("cookie 解密失败")
	// ErrNoYTCookies 未找到 YouTube 登录 cookie。
	ErrNoYTCookies = errors.New("未找到 YouTube 登录 cookie")
	// ErrUnsupportedOS 当前系统不支持浏览器自动导出（Windows v20 app-bound）。
	ErrUnsupportedOS = errors.New("当前系统暂不支持浏览器读取，请改用 cookies.txt 方式")
)

// Cookie 是 Netscape cookies.txt 中的一条记录。
type Cookie struct {
	Domain            string
	HttpOnly          bool
	IncludeSubdomains bool
	Path              string
	Secure            bool
	Expires           int64 // unix 秒；0 = 会话 cookie
	Name              string
	Value             string
}

// chromeEpochDelta 是 Chrome expires_utc 的 1601-01-01 纪元与 unix 纪元的秒差。
const chromeEpochDelta = 11644473600

// ParseNetscape 解析 Netscape cookies.txt 内容：
// # 注释行跳过（#HttpOnly_ 前缀表示该 cookie 为 HttpOnly），空行跳过，
// 字段制表符分隔（domain flag path secure expiry name value），畸形行跳过。
func ParseNetscape(data []byte) ([]Cookie, error) {
	var out []Cookie
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.TrimSpace(line) == "" {
			continue
		}
		httpOnly := false
		if strings.HasPrefix(line, "#HttpOnly_") {
			httpOnly = true
			line = line[len("#HttpOnly_"):]
		} else if strings.HasPrefix(line, "#") {
			continue
		}
		if c, ok := parseCookieLine(line, httpOnly); ok {
			out = append(out, c)
		}
	}
	return out, nil
}

// parseCookieLine 解析一行 7 字段制表符分隔记录；畸形行返回 ok=false。
func parseCookieLine(line string, httpOnly bool) (Cookie, bool) {
	f := strings.Split(line, "\t")
	if len(f) < 7 || f[0] == "" || f[5] == "" {
		return Cookie{}, false
	}
	expires, err := strconv.ParseInt(f[4], 10, 64)
	if err != nil {
		expires = 0
	}
	return Cookie{
		Domain:            f[0],
		HttpOnly:          httpOnly,
		IncludeSubdomains: strings.EqualFold(f[1], "TRUE"),
		Path:              f[2],
		Secure:            strings.EqualFold(f[3], "TRUE"),
		Expires:           expires,
		Name:              f[5],
		Value:             strings.Join(f[6:], "\t"),
	}, true
}

// WriteNetscape 以 Netscape 格式写出 cookie 文件（权限 0600，.tmp+rename 原子写）。
func WriteNetscape(path string, cookies []Cookie) error {
	return writeFileAtomic(path, marshalNetscape(cookies), 0o600)
}

// marshalNetscape 把 cookie 列表序列化为 Netscape 格式文本（不落盘，
// 供 SetPastedLogin 先校验再一次性写出）。
func marshalNetscape(cookies []Cookie) []byte {
	var b strings.Builder
	b.WriteString("# Netscape HTTP Cookie File\n")
	b.WriteString("# This file was generated by music-tui. Do not edit.\n")
	for _, c := range cookies {
		if c.HttpOnly {
			b.WriteString("#HttpOnly_")
		}
		b.WriteString(c.Domain)
		b.WriteString("\t")
		if c.IncludeSubdomains {
			b.WriteString("TRUE")
		} else {
			b.WriteString("FALSE")
		}
		b.WriteString("\t" + c.Path + "\t")
		if c.Secure {
			b.WriteString("TRUE")
		} else {
			b.WriteString("FALSE")
		}
		b.WriteString("\t" + strconv.FormatInt(c.Expires, 10))
		b.WriteString("\t" + c.Name + "\t" + c.Value + "\n")
	}
	return []byte(b.String())
}

// writeFileAtomic 原子写盘：先写 .tmp 再 rename（0600 用于敏感文件）。
// Windows 上 rename 目标已存在时失败，先移除目标再重试
// （POSIX rename 本身原子替换，不会走到重试分支）。
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, perm); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		if rmErr := os.Remove(path); rmErr != nil && !os.IsNotExist(rmErr) {
			return err
		}
		return os.Rename(tmp, path)
	}
	return nil
}

// isYouTubeDomain 判断 cookie 域是否属于 YouTube（含 music 子域）。
func isYouTubeDomain(host string) bool {
	switch host {
	case "youtube.com", ".youtube.com", "www.youtube.com", ".www.youtube.com",
		"music.youtube.com", ".music.youtube.com":
		return true
	}
	return false
}

// chromeEpochToUnix 把 Chrome 的 expires_utc（1601-01-01 起微秒）转为 unix 秒；
// 0 → 会话 cookie（0）；小值（<1e12）视为已是 unix 秒直接透传。
func chromeEpochToUnix(us int64) int64 {
	if us <= 0 {
		return 0
	}
	if us < 1e12 {
		return us
	}
	return us/1_000_000 - chromeEpochDelta
}

// ---- 浏览器 cookie 导出 ----

// browserPaths 描述各浏览器在各平台的配置目录与 keychain 标识。
type browserPaths struct {
	linuxDir  string // Linux: ~/.config 下的目录
	macDir    string // macOS: ~/Library/Application Support 下的目录
	keychain  string // macOS keychain account（"Chrome" 等）
	extraDirs []string
}

var browserDirMap = map[string]browserPaths{
	"chrome":   {linuxDir: "google-chrome", macDir: "Google/Chrome", keychain: "Chrome"},
	"chromium": {linuxDir: "chromium", macDir: "Chromium", keychain: "Chromium"},
	"brave":    {linuxDir: "brave-browser", macDir: "BraveSoftware/Brave-Browser", keychain: "Brave", extraDirs: []string{"BraveSoftware/Brave-Browser"}},
	"edge":     {linuxDir: "microsoft-edge", macDir: "Microsoft Edge", keychain: "Microsoft Edge"},
	"vivaldi":  {linuxDir: "vivaldi", macDir: "Vivaldi", keychain: "Vivaldi"},
	"opera":    {linuxDir: "opera", macDir: "com.operasoftware.Opera", keychain: "Opera"},
}

// ExportBrowserCookies 自研解密浏览器 cookie（v10/v11/macOS），只导出
// youtube 域 cookie，写 Netscape 格式文件（0600）。错误可区分：
// ErrBrowserNotFound / ErrDecryptFailed / ErrNoYTCookies。
func ExportBrowserCookies(browser, outPath string) error {
	if runtime.GOOS != "linux" && runtime.GOOS != "darwin" {
		return fmt.Errorf("%w（%s）", ErrUnsupportedOS, runtime.GOOS)
	}
	bp, ok := browserDirMap[browser]
	if !ok {
		return fmt.Errorf("%w: 不支持的浏览器 %q", ErrBrowserNotFound, browser)
	}
	profileDir, err := findProfileDir(bp)
	if err != nil {
		return err
	}
	dbPath := filepath.Join(profileDir, "Cookies")
	db, cleanup, err := openCookiesDB(dbPath)
	if err != nil {
		return fmt.Errorf("%w: 无法读取 cookie 数据库: %v", ErrBrowserNotFound, err)
	}
	defer cleanup()

	metaVersion := readMetaVersion(db)
	keys := buildPlatformKeys(browser, metaVersion)

	rows, err := queryCookieRows(db)
	if err != nil {
		return fmt.Errorf("读取 cookie 表失败: %w", err)
	}

	var out []Cookie
	failed := 0
	for _, r := range rows {
		if !isYouTubeDomain(r.hostKey) {
			continue
		}
		value := r.value
		if len(r.encryptedValue) > 0 && value == "" {
			dec, ok := decryptValue(r.encryptedValue, keys)
			if !ok {
				failed++
				continue
			}
			value = dec
		}
		if value == "" {
			continue
		}
		out = append(out, Cookie{
			Domain:            r.hostKey,
			HttpOnly:          r.httponly,
			IncludeSubdomains: strings.HasPrefix(r.hostKey, "."),
			Path:              r.path,
			Secure:            r.secure,
			Expires:           chromeEpochToUnix(r.expiresUtc),
			Name:              r.name,
			Value:             value,
		})
	}
	if len(out) == 0 {
		if failed > 0 {
			return fmt.Errorf("%w: %d 条 YouTube cookie 解密失败", ErrDecryptFailed, failed)
		}
		return ErrNoYTCookies
	}
	return WriteNetscape(outPath, out)
}

// findProfileDir 探测浏览器配置目录（Default profile）；找不到返回
// ErrBrowserNotFound。Linux 取 ~/.config（XDG），macOS 取
// ~/Library/Application Support。
func findProfileDir(bp browserPaths) (string, error) {
	cfgRoot, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("获取用户配置目录失败: %w", err)
	}
	var candidates []string
	if runtime.GOOS == "darwin" {
		candidates = []string{filepath.Join(cfgRoot, bp.macDir)}
	} else {
		candidates = []string{filepath.Join(cfgRoot, bp.linuxDir)}
		for _, d := range bp.extraDirs {
			candidates = append([]string{filepath.Join(cfgRoot, d)}, candidates...)
		}
	}
	for _, root := range candidates {
		// 优先 Default profile；Opera 等无 profile 层级的浏览器直接看根目录
		for _, dir := range []string{filepath.Join(root, "Default"), root} {
			if fi, err := os.Stat(filepath.Join(dir, "Cookies")); err == nil && !fi.IsDir() {
				return dir, nil
			}
		}
	}
	return "", fmt.Errorf("%w: 未找到浏览器配置目录（%s）", ErrBrowserNotFound, strings.Join(candidates, " / "))
}

// openCookiesDB 只读打开 Chrome Cookies 数据库；浏览器运行中直开失败时
// 复制 DB（含 WAL/SHM）到临时目录再打开（同 yt-dlp 策略）。
func openCookiesDB(dbPath string) (*sql.DB, func(), error) {
	ro, err := sql.Open("sqlite", "file:"+dbPath+"?mode=ro")
	if err == nil {
		if err = ro.Ping(); err == nil {
			return ro, func() { ro.Close() }, nil
		}
		ro.Close()
	}
	tmp, err := os.MkdirTemp("", "music-tui-cookies-*")
	if err != nil {
		return nil, nil, err
	}
	base := filepath.Base(dbPath)
	for _, name := range []string{dbPath, dbPath + "-wal", dbPath + "-shm"} {
		if fi, err := os.Stat(name); err == nil && !fi.IsDir() {
			src, err := os.Open(name)
			if err != nil {
				continue
			}
			dst, err := os.Create(filepath.Join(tmp, filepath.Base(name)))
			if err != nil {
				src.Close()
				continue
			}
			_, _ = ioCopy(src, dst)
			src.Close()
			dst.Close()
		}
	}
	db, err := sql.Open("sqlite", filepath.Join(tmp, base))
	if err != nil {
		os.RemoveAll(tmp)
		return nil, nil, err
	}
	if err := db.Ping(); err != nil {
		db.Close()
		os.RemoveAll(tmp)
		return nil, nil, err
	}
	return db, func() {
		// 复制路径的 db 句柄由本 cleanup 关闭（直开路径由调用方在分支内 Close）
		_ = db.Close()
		_ = os.RemoveAll(tmp)
	}, nil
}

// ioCopy 复制内容（避免与 io 包命名冲突的内部小工具）。
func ioCopy(dst *os.File, src *os.File) (int64, error) {
	return dst.ReadFrom(src)
}

// readMetaVersion 读 meta 表 version 字段；缺表/缺行/解析失败返回 0。
func readMetaVersion(db *sql.DB) int {
	var v string
	if err := db.QueryRow("SELECT value FROM meta WHERE key='version'").Scan(&v); err != nil {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimSpace(v))
	if err != nil {
		return 0
	}
	return n
}

// cookieRow 是 cookies 表的一行。
type cookieRow struct {
	hostKey        string
	name           string
	value          string
	encryptedValue []byte
	path           string
	expiresUtc     int64
	secure         bool
	httponly       bool
}

// queryCookieRows 读取 cookies 表全部行；secure/httponly 列名兼容新旧版本。
func queryCookieRows(db *sql.DB) ([]cookieRow, error) {
	secureCol, httpCol := cookieColumnNames(db)
	q := fmt.Sprintf("SELECT host_key, name, value, encrypted_value, path, expires_utc, %s, %s FROM cookies", secureCol, httpCol)
	rows, err := db.Query(q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []cookieRow
	for rows.Next() {
		var r cookieRow
		if err := rows.Scan(&r.hostKey, &r.name, &r.value, &r.encryptedValue, &r.path, &r.expiresUtc, &r.secure, &r.httponly); err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// cookieColumnNames 探测 cookies 表的 secure/httponly 列名（旧版 Chrome
// 为 secure/httponly，新版为 is_secure/is_httponly）。
func cookieColumnNames(db *sql.DB) (secure, httponly string) {
	secure, httponly = "is_secure", "is_httponly"
	rows, err := db.Query("PRAGMA table_info(cookies)")
	if err != nil {
		return secure, httponly
	}
	defer rows.Close()
	names := map[string]bool{}
	for rows.Next() {
		var cid, notnull, pk int
		var name, typ string
		var dflt any
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			continue
		}
		names[name] = true
	}
	if !names["is_secure"] && names["secure"] {
		secure = "secure"
	}
	if !names["is_httponly"] && names["httponly"] {
		httponly = "httponly"
	}
	return secure, httponly
}

// chromeKeys 保存解密所需密钥与 meta_version。
type chromeKeys struct {
	v10            [][]byte // v10 候选密钥（依次尝试；含 empty key 兜底）
	v11            []byte   // v11 keyring 密钥（Linux；可能为 nil）
	empty          []byte   // empty key（v11 无 keyring 时兜底）
	metaVersion    int
	macLegacyPlain bool // macOS 旧明文 cookie（无版本前缀）原样返回（yt-dlp 同款）
}

// buildPlatformKeys 按平台构建解密密钥：
//   - Linux：v10 固定 "peanuts" + empty 兜底；v11 尝试 keyring（Secret Service）。
//     不读 Local State 的 encrypted_key——该字段仅 Windows 使用（DPAPI），
//     yt-dlp Linux 分支同样只用 peanuts/keyring；读取它反而会挤掉正确密钥
//   - macOS：security CLI 取钥匙串密码，PBKDF2 1003 迭代；
//     无版本前缀的旧明文 cookie 原样返回（macLegacyPlain）
func buildPlatformKeys(browser string, metaVersion int) *chromeKeys {
	empty := deriveChromeKey(nil, linuxKeyIterations)
	keys := &chromeKeys{empty: empty, metaVersion: metaVersion}
	switch runtime.GOOS {
	case "darwin":
		bp, ok := browserDirMap[browser]
		if ok {
			if pw, err := macKeychainPassword(bp.keychain); err == nil && pw != "" {
				keys.v10 = [][]byte{deriveChromeKey([]byte(pw), macKeyIterations)}
			}
		}
		keys.macLegacyPlain = true
	case "linux":
		keys.v10 = [][]byte{deriveChromeKey([]byte("peanuts"), linuxKeyIterations), empty}
		keys.v11 = v11KeyFunc(browser)
	}
	return keys
}

// decryptValue 按版本前缀解密一条 cookie 值。
//   - v10：AES-128-CBC，候选密钥依次尝试（peanuts → empty）
//   - v11：Linux keyring 密钥；keyring 不可用降级 empty key
//   - 其他：macOS 旧明文 cookie（无前缀）原样返回；其余平台无法处理
func decryptValue(encrypted []byte, keys *chromeKeys) (string, bool) {
	if len(encrypted) < 4 {
		return "", false
	}
	switch string(encrypted[:3]) {
	case v10Prefix:
		s, err := decryptV10Multi(encrypted, keys.v10, keys.metaVersion)
		return s, err == nil
	case v11Prefix:
		var candidates [][]byte
		if len(keys.v11) > 0 {
			candidates = append(candidates, keys.v11)
		}
		candidates = append(candidates, keys.empty)
		s, err := decryptV10Multi(encrypted, candidates, keys.metaVersion)
		return s, err == nil
	default:
		// macOS 上非 v10/v11 前缀是旧明文格式（Chromium os_crypt_mac 老版本），
		// yt-dlp MacChromeCookieDecryptor 对 other 前缀直接返回原值
		if keys.macLegacyPlain {
			return string(encrypted), true
		}
		return "", false
	}
}

// v11KeyFunc 读取 Linux keyring 中 Chrome v11 加密密钥（测试可注入）。
var v11KeyFunc = linuxV11Key

// macKeychainPassword 用 security CLI 读取 macOS 钥匙串中的 Chrome 密码
// （service "Chrome Safe Storage" 等）。仅 macOS 可用。
func macKeychainPassword(account string) (string, error) {
	if account == "" {
		return "", errors.New("keychain account 为空")
	}
	out, err := exec.Command("security", "find-generic-password",
		"-w", "-a", account, "-s", account+" Safe Storage").Output()
	if err != nil {
		return "", fmt.Errorf("security 读取钥匙串失败: %w", err)
	}
	return strings.TrimRight(string(out), "\n"), nil
}

// cookiesFromHeader 把单行 "name=value; ..." Cookie header 转为 Netscape
// cookie 列表（域 .youtube.com、Secure、会话 cookie），供 yt-dlp 使用。
func cookiesFromHeader(header string) ([]Cookie, error) {
	pairs := parseCookieHeader(header)
	if len(pairs) == 0 {
		return nil, errors.New("Cookie header 为空")
	}
	out := make([]Cookie, 0, len(pairs))
	for _, p := range pairs {
		out = append(out, Cookie{
			Domain:            ".youtube.com",
			IncludeSubdomains: true,
			Path:              "/",
			Secure:            true,
			Name:              p.Name,
			Value:             p.Value,
		})
	}
	return out, nil
}

// looksLikeNetscape 判断文件内容是否已是 Netscape 格式
// （含制表符分隔字段，或以 # 注释开头）。
func looksLikeNetscape(data []byte) bool {
	s := string(data)
	return strings.Contains(s, "\t") || strings.HasPrefix(strings.TrimSpace(s), "#")
}
